### ISSUE TITLE
Select Monero Folder

### ISSUE THREAD

**Issue by wwinter86** [WeebDataHoarder/p2pool-compose#4]
Is there an option to select Monero folder like you can with —data-dir=

**Comment by WeebDataHoarder** [comment]
You should be able to create a `docker-compose.override.yml` file where you change the monero section:
```
version: "2.2"
services:
  monero:
    volumes:
      - /YOUR/DESIRED/FOLDER:/var/monero:rw
      - "${HUGEPAGES_MOUNT}:/dev/hugepages:rw"
```
